//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahangthucung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int MessageId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
