//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahangthucung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITHUCUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAITHUCUNG()
        {
            this.THUCUNGs = new HashSet<THUCUNG>();
        }
    
        public int MaLoaiTC { get; set; }
        public string TenLoaiTC { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUCUNG> THUCUNGs { get; set; }
    }
}
