//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahangthucung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public int MaThanhToan { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<decimal> TongTienThanhToan { get; set; }
        public Nullable<int> TrangThaiThanhToan { get; set; }
    
        public virtual DONDATHANG DONDATHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
